language: java
jdk:
- openjdk6
- oraclejdk7

install:
  - ls /usr/lib/jvm/java-6-openjdk-amd64/bin/
  - ls /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/
  - mvn install -DskipTests=true

script: mvn test

after_success:
  - mvn clean test jacoco:report coveralls:report
  
 
notifications:
  email:
    - richard.vannieuwenhoven@adesso.at
    - elonen@iki.fi